name: Go

on:
  - push
  - pull_request

jobs:

  semantic-release:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
      - name: Run semantic-release
        if: github.repository == 'leo220yuyaodog/oss' && github.event_name == 'push'
        run: |
          npm install --save-dev semantic-release@17.2.4
          npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
